# -*- coding: utf-8 -*-
"""Shuffle + Augment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11W5A6nqosSoltvBjwIPfOGPM4RURC2ii
"""

!kaggle datasets download brahimhalilatay/tumtum
!unzip tumtum.zip > /dev/null

!unzip /content/tumtum.zip

import os
train_images = '/content/tum/images'
train_labels = '/content/tum/labels'

print('Number of total images: ' + str(len(os.listdir(train_images))))
print('Number of total labels: ' + str(len(os.listdir(train_labels))))

import os
import shutil
import random

# Kaynak klasörler
images_dir = "/content/tum/images"
labels_dir = "/content/tum/labels"

# Hedef klasörler
output_dirs = {
    "train": {"images": "dataset/train/images", "labels": "dataset/train/labels"},
    "test": {"images": "dataset/test/images", "labels": "dataset/test/labels"},
    "valid": {"images": "dataset/valid/images", "labels": "dataset/valid/labels"},
}

# Hedef klasörleri oluştur
for split in output_dirs.values():
    os.makedirs(split["images"], exist_ok=True)
    os.makedirs(split["labels"], exist_ok=True)

# Tüm image dosyalarını al ve eşleştir
image_files = [f for f in os.listdir(images_dir) if f.endswith(".jpg")]
random.shuffle(image_files)  # Rastgele karıştırma

num_total = len(image_files)
num_train = int(num_total * 0.7)
num_valid = int(num_total * 0.15)
num_test = num_total - num_train - num_valid

splits = {
    "train": image_files[:num_train],
    "valid": image_files[num_train:num_train + num_valid],
    "test": image_files[num_train + num_valid:]
}

# Dosyaları ilgili klasörlere taşı
for split, files in splits.items():
    for file in files:
        img_src = os.path.join(images_dir, file)
        label_src = os.path.join(labels_dir, file.replace(".jpg", ".txt"))

        img_dst = os.path.join(output_dirs[split]["images"], file)
        label_dst = os.path.join(output_dirs[split]["labels"], file.replace(".jpg", ".txt"))

        shutil.move(img_src, img_dst)
        if os.path.exists(label_src):  # Label dosyasını taşı
            shutil.move(label_src, label_dst)

import os
import cv2
import numpy as np
import albumentations as A
from albumentations.core.bbox_utils import convert_bboxes_to_albumentations, convert_bboxes_from_albumentations

# Albumentations kütüphanesiyle veri artırma işlemleri
augmentation_process = A.Compose(
    [
        A.HorizontalFlip(p=0.5),  # Yatay çevirme
        A.VerticalFlip(p=0.5),  # Dikey çevirme
        A.Rotate(limit=20, border_mode=cv2.BORDER_CONSTANT, p=0.5),  # Döndürme
        A.ShiftScaleRotate(shift_limit=0.1, scale_limit=0.1, rotate_limit=10, border_mode=cv2.BORDER_CONSTANT, p=0.5),
        A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2, p=0.5),
        A.CLAHE(clip_limit=2.0, tile_grid_size=(8, 8), p=0.5),
        A.ElasticTransform(alpha=1, sigma=50, alpha_affine=50, p=0.5),
        A.Sharpen(alpha=(0.2, 0.5), lightness=(0.5, 1.0), p=0.5),
        A.Resize(height=640, width=640, p=1),
    ],
    bbox_params=A.BboxParams(format='yolo', label_fields=['class_labels'])
)

# Veri artırma fonksiyonu
def augment_and_save_yolo(image_path, label_path, output_image_dir, output_label_dir, num_augmentations=4):
    """
    YOLO formatındaki bir X-ray görüntüsüne veri artırma uygular ve sonuçları kaydeder.

    Args:
        image_path (str): Orijinal görüntü dosya yolu
        label_path (str): Orijinal etiket dosya yolu
        output_image_dir (str): Augmente edilmiş görüntülerin kaydedileceği klasör
        output_label_dir (str): Augmente edilmiş etiketlerin kaydedileceği klasör
        num_augmentations (int): Üretilecek augmentasyon sayısı
    """

    # Görüntüyü yükle
    image = cv2.imread(image_path)
    if image is None:
        print(f"Görüntü yüklenemedi: {image_path}")
        return

    # YOLO etiketlerini yükle
    with open(label_path, "r") as f:
        bboxes = []
        class_labels = []
        for line in f:
            elements = line.strip().split()
            class_id = int(elements[0])  # Sınıf ID'sini oku
            bbox = list(map(float, elements[1:]))  # Bounding box koordinatlarını oku
            bboxes.append(bbox)
            class_labels.append(class_id)

    # Çıkış klasörlerini oluştur
    os.makedirs(output_image_dir, exist_ok=True)
    os.makedirs(output_label_dir, exist_ok=True)

    for i in range(num_augmentations):
        # Veri artırma işlemi
        augmented = augmentation_process(image=image, bboxes=bboxes, class_labels=class_labels)
        augmented_image = augmented["image"]
        augmented_bboxes = augmented["bboxes"]
        augmented_class_labels = augmented["class_labels"]

        # Yeni dosya adını oluştur
        file_name = os.path.splitext(os.path.basename(image_path))[0]
        output_image_path = os.path.join(output_image_dir, f"{file_name}_aug_{i}.jpg")
        output_label_path = os.path.join(output_label_dir, f"{file_name}_aug_{i}.txt")

        # Augmente edilmiş görüntüyü kaydet
        cv2.imwrite(output_image_path, augmented_image)

        # Augmente edilmiş etiketleri kaydet
        with open(output_label_path, "w") as f:
            for bbox, class_id in zip(augmented_bboxes, augmented_class_labels):
                f.write(f"{class_id} {' '.join(map(str, bbox))}\n")

        print(f"Görüntü ve etiket kaydedildi: {output_image_path}, {output_label_path}")

# Dataset klasör yolları
dataset_root = "/content/dataset"  # Ana dataset klasörü
splits = ["train", "valid", "test"]  # Veri seti bölümleri

for split in splits:
    input_image_dir = os.path.join(dataset_root, split, "images")
    input_label_dir = os.path.join(dataset_root, split, "labels")
    output_image_dir = os.path.join(dataset_root, split, "images")
    output_label_dir = os.path.join(dataset_root, split, "labels")

    if not os.path.exists(input_image_dir) or not os.path.exists(input_label_dir):
        print(f"Uyarı: {split} seti için 'images' veya 'labels' klasörü eksik. Atlanıyor...")
        continue

    # Görüntü ve etiket dosyalarını eşleştir (jpg ve png)
    image_files = [f for f in os.listdir(input_image_dir) if f.endswith((".jpg", ".png"))]

    for image_file in image_files:
        image_path = os.path.join(input_image_dir, image_file)
        label_path = os.path.join(input_label_dir, os.path.splitext(image_file)[0] + ".txt")
        if os.path.exists(label_path):
            augment_and_save_yolo(image_path, label_path, output_image_dir, output_label_dir)